name: 'CD'

on:
  push:
    branches:
    - dev
  pull_request:


defaults:
  run:
    shell: bash
    working-directory: ./Infra/aws-python-http-api-vote-store

jobs:
  serverless:
    name: 'Serverless'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Serverless Deploy
      run: |
        pwd
        npm i -g serverless
        serverless --org=tomeriffic deploy

