name: CI

on: [push]

jobs:

  #swift-build:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build
  #    run: swift build -v
  #  - name: Run tests
  #    run: swift test -v
  
  infra-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Change to Infra Directory
      run: |
        cd Infra
        cd aws-python-http-api-vote-store
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=5 $(git ls-files '*.py')
